# Generated by Django 4.2.7 on 2023-12-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_body_en_post_body_ru_post_body_uz_post_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
    ]
