# Generated by Django 4.2.7 on 2023-12-07 14:07

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_post_body_en_remove_post_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_uz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='post',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'body'), required_languages=(), virtual_fields=True),
        ),
    ]
