# Generated by Django 4.2.7 on 2023-12-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IncludeExclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('duration', models.CharField(max_length=256)),
                ('person_count', models.IntegerField()),
                ('overview', models.TextField()),
                ('itinerary', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('archived', 'в архиве'), ('discount', 'скидка')], max_length=30)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.country')),
                ('exclude', models.ManyToManyField(related_name='tour_exclude', to='tour.includeexclude')),
                ('include', models.ManyToManyField(related_name='tour_include', to='tour.includeexclude')),
            ],
        ),
        migrations.CreateModel(
            name='TourImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tour/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='destination/')),
                ('city', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.country')),
            ],
        ),
    ]
