# Generated by Django 4.2.7 on 2023-12-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_destination_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='tourimg',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_img', to='tour.tour'),
        ),
    ]
