# Generated by Django 4.2.7 on 2023-12-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_remove_country_name_en_remove_destination_about_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='about_uz',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='city_uz',
        ),
        migrations.RemoveField(
            model_name='includeexclude',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='includeexclude',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration_uz',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='itinerary_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='itinerary_uz',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='overview_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='overview_uz',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title_uz',
        ),
    ]
