# Generated by Django 4.2.7 on 2023-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_remove_country_name_ru_remove_country_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='city_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='city_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='includeexclude',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='includeexclude',
            name='name_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='overview_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='overview_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
