# Generated by Django 4.2.7 on 2023-12-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tour_discount_price_alter_tourimg_tour'),
        ('cart', '0007_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitemtour', to='tour.tour'),
        ),
    ]
