# Generated by Django 4.2.7 on 2023-12-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_create_at_alter_orderitem_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='amount',
        ),
    ]
