# Generated by Django 4.2.7 on 2023-12-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_total_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart',
            new_name='order',
        ),
    ]
